services:
  - type: web
    name: face-recognition-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash render_start.sh"
    plan: starter
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PORT
        value: 8000
      - key: PYTHONUNBUFFERED
        value: 1