name: Build and deploy Docker app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FF56A81D86264FB390DD66781788CE08 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_85BE9F3303D4450F9A0BF0AB92CB95D1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4F356318E4E747D9B1305A45F81FDDBE }}

      - name: Build Docker image
        run: |
          docker build -t face-recg:latest .

      - name: Push and Deploy to Azure Web App for Containers
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'face-recg' # your Azure Web App name
          images: 'face-recg:latest'
